application: tuxtejas
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|jpeg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|jpeg))

- url: .*
  script: main.py
